# k8s-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-api-app
  template:
    metadata:
      labels:
        app: kubernetes-api-app
    spec:
      containers:
      - name: kubernetes-api-app
        image: kubernetesapiapp:latest # Replace this with your actual image name
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api-service
spec:
  selector:
    app: kubernetes-api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
